- Cargo.toml
This fixes the issue with Windows not building because of a bad version of dwrote-rs (breaking changes in patch update).
> Fix Windows build

- src/loaders/freetype.rs
> Reset character size after rasterizing on FreeType

- src/loaders/directwrite.rs
> Fix DirectWrite raster bounds

- src/loaders/directwrite.rs
I don't know much about fonts so these values were basically experimentally determined, but they seem to work in Alacritty.
> Implement the origin method on DirectWrite

- src/error.rs
self-explanatory. allows anyone to use the error as a trait object if that benefits them
> add error impls for error types

- src/source.rs
- src/sources/fontconfig.rs
Uses the same algorithm as [fc-match](https://gitlab.freedesktop.org/fontconfig/fontconfig/blob/master/fc-match/fc-match.c).
Partially fixes #25
> Resolve default fonts using fontconfig.

- Cargo.toml
- src/loader.rs
- src/loaders/core_text.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
This change implements looking up glyphs by their name, which is useful when dealing with fonts that may not have a cmap (in my case certain CFF files).
Implementing this outside fontkit, although possible, is quite cumbersome as I basically need to mirror all the platform-specific dependencies and compilation flags.
There's two rough edges at the moment that I'm happy to try and fix up if you're generally interested in this change. One being the FFI binding for `CTFontGetGlyphWithName` that should probably move into the `core-text` crate, and the other that there appears to be no simple way to do name-based lookup using the DirectWrite APIs.
Let me know what you think!
> implement glyph_by_name method

- src/sources/fontconfig.rs
Fixes #42.
`FcFontMatch` only returns the best matching font, but we need to return a whole list (so that, for example, querying `sans-serif` returns all of the variants of DejaVu Sans, and not just the regular one). I'm not actually sure that `FcFontSort` is the right function (as opposed to `FcFontList`), but it's the one that `fc-match` uses.
> Return a whole list of families in fontconfig.

- Cargo.toml
- examples/fallback.rs
- src/loader.rs
- src/loaders/core_text.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
Note: this version will fail to compile unless the dwrote dep is manually patched to git master, as a release hasn't been done with https://github.com/servo/dwrote-rs/pull/32
An additional concern is performance, as the font data will need to be copied each time a fallback font is used.
Addresses #37
> Add prototype fallback API for DirectWrite

- examples/list-fonts.rs
Before:
```
+---------------------------------------+----------------------------------+----------------------------------+--------+--------+---------+
| PostScript Name                       | Name                             | Family                           | Style  | Weight | Stretch |
+---------------------------------------+----------------------------------+----------------------------------+--------+--------+---------+
| AndaleMono                            | Andale Mono                      | Andale Mono                      | Normal | 400    | 1       |
+---------------------------------------+----------------------------------+----------------------------------+--------+--------+---------+
| CourierNewPSMT                        | Courier New                      | Andale …
```
> Use a simpler table format.

- src/loaders/core_text.rs
I believe this fixes [#43](https://github.com/pcwalton/font-kit/issues/43). I've tested this with Raqote and ran font-kit's tests. It appears to work correctly with this subtraction.
> Flip CoreGraphics origin in the y axis (issue #43)

- src/source.rs
According to https://www.w3.org/Style/Examples/007/fonts.en.html
Closes #58
> Use Impact as a default fantasy font on Windows.

- src/loaders/core_text.rs
- src/loaders/freetype.rs
Previously, `glyph_for_char` in CoreText and FreeType loaders were always
returned `Some`, instead of checking results.
Closes #38
> Check results in Loader::glyph_for_char.

- src/canvas.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
This will be used to implement proper origin support in the freetype and
directwrite loaders. Currently those loaders either ignore the origin
or only use the fractional part.
> Support blits with an offset

- Cargo.toml
- examples/render-glyph.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
- src/test.rs
This change makes the positioning of in the canvas consistent between the
loaders on all platforms. It adopts the convention of having the origin at the
top left with +y going down. Glyphs with their baseline at the specified
offset. This follows the convention of cairo and HTML canvas.
The version is bumped because of this behaviour change.
>  Properly support the offset in dwrite and freetype loaders.

- Cargo.toml
- src/canvas.rs
- src/family.rs
- src/family_handle.rs
- src/font.rs
- src/handle.rs
- src/lib.rs
- src/loader.rs
- src/loaders/core_text.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
- src/loaders/mod.rs
- src/matching.rs
- src/source.rs
- src/sources/core_text.rs
- src/sources/directwrite.rs
- src/sources/fontconfig.rs
- src/sources/fs.rs
- src/sources/mem.rs
- src/sources/multi.rs
- src/test.rs
This avoids building the `dirs` crate on Windows where it is unused.
> Upgrade to 2018 edition and reduce unnecessary dependencies

- examples/render-glyph.rs
- src/canvas.rs
- src/lib.rs
- src/loader.rs
- src/loaders/core_text.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
- src/test.rs
> Add a FontTransform to allow arbitrary transformations on glyphs.

- src/loaders/freetype.rs
Ran into this with the [XITS.otf](https://rynx.org/rex/xits.otf) font. Character 𝑗.
> Fix a bug when the last curve on a contour is a cubic using the first point as point2

- README.md
- src/lib.rs
Currently this example leaves the canvas blank.
> fix README example so that glyph isn't rendered off canvas

- src/loaders/directwrite.rs
- src/test.rs
Fixes #85 
- `raster_bounds` was returning a rectangle at origin (0,0) whereas the origin of the bounds rectangle returned by `get_alpha_texture_bounds` is not (0,0). This caused offsetting origin calculation to be off when passed to `rasterize_glyph` which caused the clipping.
Offsetting origin calculation that I am referring to is:
https://github.com/pcwalton/font-kit/blob/6801dce15cbc75448d99420eeebbe8c867585f36/examples/render-glyph.rs#L133-L136
This change sets the origin of the `raster_bounds` rectangle so that the origin offset arithmetic actually holds for directwrite.
```
c:\repositories\rust\font-kit>cargo run --example render-glyph ArialMT { 32
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `target\debug\examples\render-glyph.exe ArialMT { 32`
glyph 94: …
```
> Fix DirectWrite raster_bounds arithmetic

- src/loaders/freetype.rs
Fixes #5.
I don't know if returning an empty string is the right thing to do when FreeType has a null family name, but at least it doesn't crash. In any case, I've verified with the following C program that FreeType will happily load a font with no family name and report no errors:
```
#include <stdio.h>
#include <ft2build.h>
#include FT_FREETYPE_H
int main()
{
FT_Library library;
FT_Face face;
FT_Init_FreeType(&library);
FT_Error error = FT_New_Face(library, "/usr/share/fonts/misc/decsess.pcf.gz", 0, &face);
if (error) {
printf("Error opening face: %s\n", FT_Error_String(error));
return 1;
}
printf("Success opening face. Family name: %s\n", face->family_name);
return 0;
}
```
> Don't crash with freetype supplies a non-null family name.

- Cargo.toml
- src/loaders/mod.rs
- src/source.rs
- src/sources/mod.rs
- src/test.rs
Hi, was looking into adding [iOS support](https://github.com/hecrj/iced/issues/51)to [Iced](https://github.com/hecrj/iced/) and found that this crate didn't have conditional compilation on iOS targets.
> Added ios support.

- Cargo.toml
When de6fabc got merged, the dependency that loaded `winapi`'s `sysinfoapi` feature got removed. This fails builds when attempting to build `font-kit` downstream (i.e. if you depend on `git = "https://github.com/pcwalton/font-kit.git"` through `Cargo.toml`), but it does *not* fail when you run `cargo build` within `font-kit`'s folder directly.
I don't know why cargo behaves that way. I assume it's a bug. Still, this fixes that behavior by making the `sysinfoapi` dependency explicit. For good measure, we make all the other `winapi` dependency features explicit to ensure this same sort of issue doesn't happen again.
> Fix build failure when downstream crates attempt to build font-kit on Windows

- Cargo.toml
- src/loader.rs
- src/loaders/directwrite.rs
- src/test.rs
This fixes the origin mismatch that happens in the fallback
implementation of raster_bounds() and matches the origin of the canvas
which makes the api more usable.
The major version is bumped because of the behaviour change.
> Use top-left as the origin for raster bounds

- src/loader.rs
- src/loaders/core_text.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
Fixes #35.
I'm unable to actually test this implementation for macOS, since I don't have convenient access to a macOS system. That being said, if it compiles I don't see any reason why this particular implementation wouldn't work.
> Add function to load OpenType font tables

- src/loaders/core_text.rs
- src/test.rs
> Stop panicking when rasterizing to a zero-size canvas in the Core Text backend.

- Cargo.toml
- src/loaders/core_text.rs
- src/loaders/directwrite.rs
- src/loaders/freetype.rs
- src/metrics.rs
- src/test.rs
> Expose the global glyph bounding box through the `metrics()` method.

- tests/select_font.rs
> Ignore a test that depends on fonts not always available.

- Cargo.toml
The old version of `fontconfig` can't parse the config files on newer operating systems (like Ubuntu 19.10 or 20.04) and applications that use it take a ton of time to load (about 1 minute in my case) after encountering these problems.
The issue is fixed by updating the version of `servo-fontconfig` in `Cargo.toml`, which in turn links to a newer version of `fontconfig` itself.
> bump servo-fontconfig to v0.5

- src/loader.rs
- tests/tests.rs
This fixes issue #141, so that Loader::raster_bounds actually returns tight raster bounds.
Previously, it returned distorted bounds due to usage of "RectF::set_origin_y"
which does not preserve Rect size.
> Fix #141 "Loader::raster_bounds" to work as intended.

- src/sources/fs.rs
I'm working on a font manager that uses font-kit and distributed using [Flatpak](flatpak.org/), this patch should allow reading fonts from outside the sandboxed too if the access to the path is given using `--filesystem=/usr/share/fonts:ro` in the application manifest.
The path is mounted later under `/var/host/run/$path`
> Sources: add flatpak specific paths

- src/loaders/freetype.rs
I just copied the type from [the underlying struct](https://github.com/servo/rust-freetype/blob/master/src/freetype.rs#L297) but if you prefer I'm happy to use the rust types and do some target_pointer_width shenanigans.
> Cast explicitly to c_long which is the underlying type

- Cargo.toml
- src/lib.rs
Hello!
I also needed the change seen in #144, so I decided to open my own PR.  Are you open to bumping this version?  In my project, I am trying to use [servo/rust-freetype](https://github.com/servo/rust-freetype) v0.5.1, but since `font-kit` currently depends on FreeType v0.4.1 I get this error during compilation:
```
error: multiple packages link to native library `freetype`, but a native library can be linked only once
package `freetype-sys v0.11.0`
... which is depended on by `freetype v0.5.1`
... which is depended on by `kosmonaut v0.1.0 (/home/twilco/projects/kosmonaut)`
links to native library `freetype`
package `servo-freetype-sys v4.0.3`
... which is depended on by `freetype v0.4.1`
... which is depended on by `font-kit v0.7.1`
... which is depended on by `kosmonaut v0.1.0 …
```
> Upgrade FreeType dep from 0.4.1 to 0.5.1

- Cargo.toml
Hello again.  Whenever it's convenient, a release following the merge of #150 would be greatly appreciated.  I bumped a minor version since #150 bumped FreeType a minor version.  Thanks!
> Bump version from 0.7.1 to 0.8.0

- .travis.yml
- Cargo.toml
This also requires log 0.4.4 as older
versions don't build with rust anymore.
> Add a minimal versions build job

- Cargo.toml
- src/loaders/directwrite.rs
- src/source.rs
Fonts like "Times New Roman" resolve to a path like C:\WINDOWS\FONTS\TIMES NEW ROMAN.TTF.
Strangely, UWP permits opening these paths, but not calling GetFinalPathNameByHandleW on
a file handle that has been opened to it. The current code path is both inefficent (we
use a path to open a file, then attempt to get the path again from that file handle) and
broken, so when a path is available we can pass it directly to DirectWrite and avoid the
entire problem.
> Avoid a permission error matching fonts under UWP.

- src/loaders/directwrite.rs
`glyph_for_char` on Windows will always return Some(0) when the given char does not exit,  It seems return None is more reasonable
> glyph_for_char return None when the given char does not exit on Windows

- src/sources/mem.rs
This PR adds a method that allows a `MemSource` to be extended dynamically after creation. It is useful when implementing an interface that assumes this is possible (for me, the motivating interface is in https://github.com/linebender/piet).
> Add method to add to a `MemSource` after creation.

- src/sources/core_text.rs
- tests/select_font.rs
When `create_handles_from_core_text_collection`, we only need to read the same path file once, and change handle to memory mode, so when load font from the handle next time, we can use the memory data.
before:
after:
> Perf select_best_match

- src/source.rs
- src/sources/multi.rs
This PR has 2 parts
1. Make `Source` inherit `Any` to allow downcasting.
2. Allow getting access to `Source`s in a `MultiSource`.
These things together allow access to the constituent sources in a multisource, for example to allow adding to a `MemSource`.
> Allow getting individual sources from a `MultiSource`.

- src/source.rs
- src/sources/core_text.rs
- src/sources/directwrite.rs
- src/sources/fontconfig.rs
- src/sources/fs.rs
- src/sources/mem.rs
- src/sources/multi.rs
The `iter`/`iter_mut` methods allow iterating through the subsources of a `MultiSource`. The `as_any`/`as_mut_any` methods are necessary for downcasting `Source`s into concrete types.
In addition, the `find_source` and `find_source_mut` methods are added as a convenience to find the first source matching the given type.
> Add `iter` to `MultiSource`, and `as_any` to `Source`

- Cargo.toml
- src/sources/fs.rs
This pull request replaces the `dirs` dependency with the `dirs-next` crate in accordance with [this Rust security advisory](https://rustsec.org/advisories/RUSTSEC-2020-0053). Closes #173.
This is my first time contributing to font-kit. Let me know if you need me to do anything else.
> Replace dirs with dirs-next

- examples/render-glyph.rs
Before this change, a garbage glyph would be rendered if a multi-byte character was used as input on the command line. Now it will render properly if the selected font supports the corresponding glyph.
Ex:
`ArialMT ä` works.
`ArialMT 心` doesn't work because Arial doesn't have the glyph.
`SimSun 心` works.
> Changed examples/render-glyph to handle multi-byte characters

- src/loaders/core_text.rs
Thank you guys for making this awesome library!
I noticed that there are a couple of places in the library where corrupted / non-standard font header file could cause panicking rather than returning a parsing error. These panics are mainly caused by out of bounds errors when slicing with wrong indices. Thus, I added some bound safety checks to return a proper parsing error when these scenarios happen. This PR does not change anything functionality-wise.
> Add bound safety checks

- src/loaders/freetype.rs
The code here just trusted the value to always to be valid, but since this may be an arbitrary font, the value may not always be valid. In my case the `usWidthClass` I'm seeing has the value 500, probably the `usWeightClass` accidentally being assigned to the `usWidthClass`.
> Fix panic when parsing invalid `usWidthClass`

- src/canvas.rs
Created new struct `BlitRgb24ToRgba32` implementing `Blit` to facilitate the conversion.
Fixes #190.
> Fix panic when converting from Rgb24 to Rgba32

- Cargo.toml
- build.rs
- src/loaders/freetype.rs
- src/sources/fontconfig.rs
servo-fontconfig statically links a vendored fontconfig library if fontconfig is not found by pkgconfig. Using a vendored fontconfig
library instead of the system fontconfig library doesn't actually work well though:
https://github.com/slint-ui/slint/issues/88
Building a vendored copy of fontconfig is also problematic because fontconfig has a lot of C dependencies, which makes it difficult to cross compile the vendored copy of fontconfig:
```
$ pkg-config fontconfig --static --libs
-lfontconfig -lfreetype -lz -lbz2 -lpng16 -lm -lm -lz -lharfbuzz -lm -lglib-2.0 -lm -lpcre -lsysprof-capture-4 -pthread -lgraphite2 -lbrotlidec -lbrotlicommon -lxml2 -lz -llzma -lm
```
Instead of using a vendored copy, with
https://github.com/yeslogic/fontconfig-rs/pull/12
yeslogic-fontconfig-sys will have a …
> switch to yeslogic-fontconfig-sys instead of servo-fontconfig

- tests/tests.rs
With this command line:
```
cargo test --features="source,loader-freetype-default"
```
Then these errors are produced:
```
error[E0428]: the name `get_vertically_hinted_glyph_outline` is defined multiple times
--> tests/tests.rs:270:1
|
226 | pub fn get_vertically_hinted_glyph_outline() {
| -------------------------------------------- previous definition of the value `get_vertically_hinted_glyph_outline` here
...
270 | pub fn get_vertically_hinted_glyph_outline() {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `get_vertically_hinted_glyph_outline` redefined here
|
= note: `get_vertically_hinted_glyph_outline` must be defined only once in the value namespace of this module
error[E0428]: the name `get_fully_hinted_glyph_outline` is defined multiple times
--> tests/tests.rs:360:1
|
316 | …
```
> fix compilation errors in tests

- src/family_name.rs
- src/properties.rs
I needed this for caching implementation and felt it easier to use font-kit's types instead of converting them into my own.
> Derive Hash for `FamilyName` and `Style`

- src/loaders/freetype.rs
I don't really understand what's going on here. All I really know is that I ran into one of the standard library's debug assertions when running some of the examples in `plotters`. I trimmed one down, but not a whole lot.
```rust
use plotters::prelude::*;
fn main() {
let mut buffer = vec![0u8; 1024 * 768 * 3];
let area = BitMapBackend::with_buffer(&mut buffer[..], (1024, 768))
.into_drawing_area()
.split_evenly((1, 2));
let _chart = ChartBuilder::on(&area[0])
.caption("Incremental Example", ("sans-serif", 20))
.build_cartesian_2d(0..10, 0..10)
.expect("Unable to build ChartContext");
}
```
Running this example without this patch using `cargo +nightly run -Zbuild-std --target=x86_64-unknown-linux-gnu` will panic:
```
thread 'main' panicked at 'unsafe precondition(s) violated: …
```
> Bail out from rendering when bitmap_buffer is null

- Cargo.toml
This is needed to avoid umaintained crate c.f. https://github.com/yeslogic/fontconfig-rs/issues/35
> Use font-config-sys 5.0

- Cargo.toml
A new release is needed to get https://github.com/servo/font-kit/issues/224 out the door
> Update to version 0.13 in preparation for release

- src/error.rs
- src/sources/core_text.rs
I ran into a bug a while back that prevent me from using the plotters library for months. I did finally figure out what was causing it: a file in my font library documented in issue #231. Removing the file fixed my issue, but the opaque problem is sure to ensnare others.
This PR adds a `LoadError(Cow<'static, str>)` variant to `SelectionError` enum. It removes `Copy` because `Cow` isn't copyable. And now when I run the test suite with the bad file in place, it reports this error, which is far and away more helpful than before.
```sh
> RUST_BACKTRACE=1 cargo test --all
...
running 5 tests
test loaders::core_text::test::test_core_text_to_css_font_stretch ... ok
test loaders::core_text::test::test_core_text_to_css_font_weight ... ok
test …
```
> bug: Add diagnostic information on font load error

- Cargo.toml
- src/lib.rs
- src/source.rs
- src/sources/fs.rs
- src/sources/mod.rs
- Use the filesystem as SystemSource on OpenHarmony
- Use [HarmonyOS Sans] as the default font family for available styles on Openharmony
[HarmonyOS Sans], which despite the name is also available in [OpenHarmony](https://gitee.com/openharmony/utils_system_resources), is really the default and only font on OpenHarmony besides some language specific NotoSans fonts.
[HarmonyOS Sans]: https://developer.huawei.com/consumer/en/doc/design-guides-V1/font-0000001157868583-V1
~~Note: So far I've only tested on a HarmonyOS phone, but since HarmonyOS Sans is also published on Gitee as part of OpenHarmony it should also be available on OpenHarmony devices. Nevertheless, I'm marking this MR as a Draft, until I've confirmed that the HarmonyOS fonts are also available on pure OpenHarmony devices.~~ …
> Add support for OpenHarmony

- .github/workflows/ci.yml
- src/loaders/freetype.rs
- Update GH actions, to fix warnings that the actions are using too old node versions
- Fix a Safety precondition violation in freetype.rs (exposed by Rust 1.78 debug assertions in the std library).
> Fix fontkit CI

- src/family_name.rs
- src/properties.rs
Fix "this URL is not a hyperlink" warning
> Fix cargo doc warning

- src/loaders/freetype.rs
I was getting incorrect bounds for glyphs after rasterizing the space(' ') glyph.
In rasterize_glyph(), there is an early return if the bitmap buffer is null (as it is a space) and because of that the char size is not reset correctly.
Then if you call raster_bounds for another glyph it loads it with the rasterize char size.
So I just removed the early return and add an else block, so the reset is called at the end.
> Reset char size even if bitmap buffer is null

- Cargo.toml
- src/loaders/freetype.rs
Instead of depending on `rust-freetype` which in turn depends on
`freetype-sys`, just depend on `freetype-sys` directly.
> Depend directly on `freetype-sys`

- Cargo.toml
c.f. https://github.com/yeslogic/fontconfig-rs/pull/40
crate `cstr` is now unmaintained. It hasnt been added to advisory-db yet.
> Use font-config-sys 6.0

- Cargo.toml
- src/sources/fs.rs
`dirs-next` is now the abandoned crate, so switch to `dirs`.
> Switch from `dirs-next` to `dirs` and release a new version

- Cargo.toml
Updates to recent cut of `pathfinder_simd` to enable building on nightly
> Bump `pathfinder_simd` to latest (0.5.4)

- .github/workflows/ci.yml
- src/canvas.rs
- tests/tests.rs
It seems that fontconfig is no longer found with the ubuntu-latest runner, which has been bumped from 22.04 to 24.04 since the last CI run.
Installing libfontconfig-dev in the runner seems to fix this.
> Add libfontconfig-dev dependency for version bump to Ubuntu 24.04

- src/sources/fs.rs
Fixed Flatpak-specific paths to align with [Flatpak documentation](https://docs.flatpak.org/en/latest/desktop-integration.html#fonts).
> Fix Flatpak-specific paths

- src/loaders/core_text.rs
- src/sources/core_text.rs
- src/sources/fs.rs
Fix issue: https://github.com/servo/font-kit/issues/258
Previous mapping was incorrect, using [-1, 1] to [0, 8]. Based on the values ranging from 'kCTFontWidthExtraCompressed' (-0.4) to 'kCTFontWidthUltraExpanded' (0.4), the corrected conversion maps CoreText font width values from [-0.4, 0.4] to [0, 8]
> Fix CoreText font width to CSS font stretch conversion

- Cargo.toml
The primary motivation for doing this is to move towards allowing Servo to eliminate older an version (0.48) of `windows-sys`.
> Upgrade dirs to 6.0.0
