src/loaders/directwrite.rs

Needs https://github.com/servo/dwrote-rs/pull/15 to be merged

Implement is_monospace for dwrite backend

---

src/loaders/freetype.rs

fix type mismatch (issue #8).

---

src/canvas.rs

Implement BlitA8ToRgb24

---

README.md

Add syntax highlighting to README snippet

---

src/sources/fontconfig.rs

Moved all unsafe code into a safe, idiomatic submodule. This should make life easier.

Fontconfig rewrite.

---

examples/list-fonts.rs
src/source.rs
src/sources/core_text.rs
src/sources/directwrite.rs
src/sources/fontconfig.rs
src/sources/fs.rs
src/sources/mem.rs
src/sources/multi.rs

This made the `list-fonts` example times faster.

Added Source::all_fonts.

---

src/matching.rs
src/source.rs

We only use one field from it, so there is no point in this structure.
Also, it's not a public type.

Remove 'Description' since it's unused.

---

src/sources/fontconfig.rs

added Drop implementation calling FcConfigDestroy for fc::Config

---

examples/render-glyph.rs

Update render-glyph according to #113

Update example to 0.5.0

---

Cargo.toml
src/test.rs

Tests are failing locally but it might be some font related stuff that would only pass on CI

Update lyon_path to 0.15

---

src/matching.rs

Prefer exact font weight matches.

---

src/source.rs

Don't panic when a font handle can't be opened.

---

Cargo.toml
src/loaders/core_text.rs

Fix `select_best_match` leaks memory on Mac

---

src/sources/core_text.rs

1. `create_handles_from_core_text_collection`: We can cache font analyze result, so the data of same path just be analyzed at first time. 
2. `create_handle_from_descriptor`: We should handle the error. Call `analyze_path` and `slurp_file` will read file twice.

Optimize(MacOS): create handle 

---

src/sources/fs.rs

Add FsSource::in_path

---

Cargo.toml

Fixes some nightly builds and gets rid of unsafe API

Bump prettytable to 0.10

---

src/loaders/freetype.rs

According to https://freetype.org/freetype2/docs/reference/ft2-library_setup.html#ft_library
> Library objects are normally created by `FT_Init_FreeType`, and destroyed with `FT_Done_FreeType`.
Currently it leaks the thread-local `FT_Libaray` memory:
```
==38981== 1,544 (400 direct, 1,144 indirect) bytes in 1 blocks are definitely lost in loss record 78 of 94
==38981==    at 0x4875058: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-arm64-linux.so)
==38981==    by 0x2B840F: ft_alloc (ftsystem.c:76)
==38981==    by 0x2B151B: ft_mem_qalloc (ftutil.c:75)
==38981==    by 0x2B1463: ft_mem_alloc (ftutil.c:54)
==38981==    by 0x2AC9FF: FT_New_Library (ftobjs.c:5496)
==38981==    by 0x2B37F3: FT_Init_FreeType (ftinit.c:224)
==38981==    by 0x1AECD7: …
```

Fix thread-local freetype library memory leak

---

Cargo.toml
examples/fallback.rs
examples/render-glyph.rs
tests/select_font.rs

Note clap 4 requires more effort - not too much, but I'd like to get these PRs in first before taking that on.

Bump float-ord and some dev-dependencies

---

examples/fallback.rs
examples/render-glyph.rs
src/family_handle.rs
src/loaders/freetype.rs
src/loaders/mod.rs
src/matching.rs
src/outline.rs
src/properties.rs
src/source.rs
src/sources/fontconfig.rs
src/sources/fs.rs
src/sources/mem.rs
src/sources/multi.rs
tests/select_font.rs
tests/tests.rs

Happy to revert or revise bits, but it would be nice to be fixing as many as possible to align with clippy's preferences, so that contributors can use clippy without being drowned in noise.

Clippy fixes

---

Cargo.toml
examples/fallback.rs
examples/render-glyph.rs

I havent played around with these example CLIs, so there is a small chance that these changes break it in some way.

Update dev-dependency clap to v4

---

src/loaders/freetype.rs

Fixes https://github.com/servo/font-kit/issues/224

Safely drop Font

---

Cargo.toml

These are the latest versions of both crates.

Update core-graphics to 0.23 and core-text to 20.1.0

---

Cargo.toml

Bump pathfinder_simd to 0.5.3

---

Cargo.toml

It would be nice to get a new release

Bump version to 0.13.1
